// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repositories.Models;

public partial class ChatMessage
{
    [Key]
    public int ChatMessageId { get; set; }

    public int? UserId { get; set; }

    public string Message { get; set; }

    public DateTime SentAt { get; set; }
    
    public bool IsRead { get; set; }

    public virtual User User { get; set; }
}