// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repositories.Models;

public partial class Order
{
    [Key]
    public int OrderId { get; set; }

    public int? CartId { get; set; }

    public int? UserId { get; set; }

    public string PaymentMethod { get; set; }

    public string BillingAddress { get; set; }

    public string OrderStatus { get; set; }

    public DateTime OrderDate { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}